INSERT INTO task (title, description, priority, user_id, deadline, status) 
VALUES
('Reunião de Equipe', 'Preparar pauta para a reunião semanal', 'LOW', 1, '2023-10-30', true),
('Relatório de Vendas', 'Gerar relatório de vendas do mês passado', 'MEDIUM', 5, '2023-11-05', false),
('Atualização do Site', 'Atualizar o conteúdo do site principal', 'HIGH', 6, '2023-11-10', true),
('Revisão do Contrato', 'Revisar e corrigir o contrato com o cliente', 'LOW', 7, '2023-11-15', false),
('Treinamento da Equipe', 'Preparar material para treinamento da equipe', 'MEDIUM', 8, '2023-11-20', true),
('Lançamento do Produto', 'Preparar evento de lançamento do novo produto', 'HIGH', 9, '2023-11-25', false),
('Orçamento para Projeto', 'Preparar orçamento para novo projeto', 'LOW', 10, '2023-11-30', true),
('Revisão de Documentação', 'Revisar documentação técnica do projeto', 'MEDIUM', 11, '2023-12-05', false),
('Entrevista de Candidatos', 'Entrevistar candidatos para a vaga aberta', 'HIGH', 12, '2023-12-10', true),
('Planejamento de Marketing', 'Rever estratégia de marketing para o próximo trimestre', 'LOW', 1, '2023-12-15', false),
('Revisão de Código', 'Revisar o código-fonte do novo recurso', 'MEDIUM', 5, '2023-12-20', true),
('Relatório Financeiro', 'Preparar relatório financeiro trimestral', 'HIGH', 6, '2023-12-25', false),
('Atualização de Aplicativo', 'Lançar atualização do aplicativo móvel', 'LOW', 7, '2023-12-30', true),
('Entrega de Projeto', 'Entregar projeto para o cliente', 'MEDIUM', 8, '2024-01-05', false),
('Testes de Software', 'Realizar testes de software para nova versão', 'HIGH', 9, '2024-01-10', true),
('Reunião de Planejamento', 'Reunião de planejamento estratégico', 'LOW', 10, '2024-01-15', false),
('Entrevista de Clientes', 'Entrevistar clientes para feedback', 'MEDIUM', 11, '2024-01-20', true),
('Desenvolvimento de Recurso', 'Desenvolver novo recurso do aplicativo', 'HIGH', 12, '2024-01-25', false),
('Teste de Segurança', 'Realizar teste de segurança do sistema', 'LOW', 1, '2024-01-30', true),
('Suporte ao Cliente', 'Atender solicitações de suporte ao cliente', 'MEDIUM', 5, '2024-02-05', false),
('Revisão de Design', 'Revisar o design do site', 'HIGH', 6, '2024-02-10', true),
('Pesquisa de Mercado', 'Realizar pesquisa de mercado para novo produto', 'LOW', 7, '2024-02-15', false),
('Treinamento em Vendas', 'Realizar treinamento em vendas para a equipe', 'MEDIUM', 8, '2024-02-20', true),
('Atualização de Documentação', 'Atualizar documentação técnica', 'HIGH', 9, '2024-02-25', false),
('Revisão de Contratos', 'Revisar todos os contratos da empresa', 'LOW', 10, '2024-03-01', true),
('Gestão de Projetos', 'Gerenciar projetos em andamento', 'MEDIUM', 11, '2024-03-06', false),
('Treinamento em TI', 'Realizar treinamento em TI para a equipe', 'HIGH', 12, '2024-03-11', true),
('Desenvolvimento de Software', 'Desenvolver novo software para o cliente', 'LOW', 1, '2024-03-16', false),
('Suporte Técnico', 'Fornecer suporte técnico aos clientes', 'MEDIUM', 5, '2024-03-21', true),
('Gestão de Recursos Humanos', 'Gerenciar recursos humanos da empresa', 'HIGH', 6, '2024-03-26', false),
('Lançamento de Campanha', 'Lançar campanha publicitária', 'LOW', 7, '2024-03-31', true),
('Revisão de Relatórios', 'Revisar relatórios financeiros', 'MEDIUM', 8, '2024-04-05', false),
('Manutenção de Equipamentos', 'Realizar manutenção dos equipamentos', 'HIGH', 9, '2024-04-10', true),
('Análise de Dados', 'Realizar análise de dados de mercado', 'LOW', 10, '2024-04-15', false),
('Treinamento em Atendimento', 'Treinamento em atendimento ao cliente', 'MEDIUM', 11, '2024-04-20', true),
('Desenvolvimento de Aplicativo', 'Desenvolver novo aplicativo móvel', 'HIGH', 12, '2024-04-25', false),
('Treinamento de Novos Funcionários', 'Realizar treinamento para novos funcionários', 'MEDIUM', 8, '2024-05-20', true),
('Pesquisa de Satisfação do Cliente', 'Realizar pesquisa de satisfação dos clientes', 'HIGH', 9, '2024-05-25', false),
('Desenvolvimento de Recurso 2', 'Desenvolver novo recurso para o aplicativo', 'LOW', 10, '2024-05-30', true),
('Revisão de Processos Internos', 'Revisar e otimizar processos internos', 'MEDIUM', 11, '2024-06-05', false),
('Treinamento em Segurança de Dados', 'Realizar treinamento em segurança de dados', 'HIGH', 12, '2024-06-10', true),
('Lançamento de Campanha 2', 'Lançar segunda campanha publicitária', 'LOW', 1, '2024-06-15', false),
('Revisão de Contratos 2', 'Revisar contratos com fornecedores', 'MEDIUM', 5, '2024-06-20', true),
('Manutenção de Equipamentos 2', 'Realizar manutenção dos equipamentos de produção', 'HIGH', 6, '2024-06-25', false),
('Avaliação de Desempenho', 'Realizar avaliação de desempenho dos funcionários', 'LOW', 7, '2024-06-30', true),
('Desenvolvimento de Aplicativo 2', 'Desenvolver segundo aplicativo móvel', 'MEDIUM', 8, '2024-07-05', false),
('Planejamento Estratégico', 'Realizar planejamento estratégico para o próximo ano', 'HIGH', 9, '2024-07-10', true),
('Entrevista de Fornecedores', 'Entrevistar novos fornecedores', 'LOW', 10, '2024-07-15', false),
('Suporte ao Cliente 2', 'Fornecer suporte técnico adicional aos clientes', 'MEDIUM', 11, '2024-07-20', true);
